#  _____                       _         _     _                 #
# / ____|                     (_)       | |   (_)                #
#| (___     __ _   _ __ ___    _   ___  | |_   _   _ __     ___  #
# \___ \   / _` | | '_ ` _ \  | | / __| | __| | | | '_ \   / _ \ #
# ____) | | (_| | | | | | | | | | \__ \ | |_  | | | | | | |  __/ #
#|_____/   \__,_|_|_|_|_|_|_|_|_| |___/  \__| |_| |_| |_|  \___| #
#                                                                #
#       | |  | | | |   (_) | | (_) | |   (_)                     #
#       | |  | | | |_   _  | |  _  | |_   _    ___   ___         #
#       | |  | | | __| | | | | | | | __| | |  / _ \ / __|        #
#       | |__| | | |_  | | | | | | | |_  | | |  __/ \__ \        #
#        \____/   \__| |_| |_| |_|  \__| |_|  \___| |___/        #

#Remove/add features to disable/enable them respectfully
EnabledFeatures: [
    #NoSandFall,
    #NoRainFall,
    #ChatUtils,
    PhysicsDisabler,
    FindTiles
]

######NoSandFall######
NoSandFall: {
    all_worlds: true,
    worlds: [
        'world',
        'world_nether',
        'world_the_end'
    ]
}

######NoRainFall######
NoRainFall: {
    all_worlds: true,
    worlds: [
        'world',
        'world_nether',
        'world_the_end'
    ]
}

######ChatUtils######
ChatUtils: {

    #See http://www.regexr.com/
    Regex: {
        #Replaces non-english characters with an empty string
        '[^\x00-\x7F§]': '',

        #Corrects all case forms of "cant" to "can't"
        '\b(c|C)(a|A)(n|N)(t|T)\b': '$1$2$3\''$4'
    }

}